package cli

import (
	"bytes"
	"fmt"
	"html/template"
	"strings"

	"github.com/MakFly/deploy-shuttle/go-cli/internal/readiness"
)

type htmlSection struct {
	Severity string
	Title    string
	Items    []htmlFinding
}

type htmlFinding struct {
	Title       string
	ID          string
	Summary     string
	Remediation string
	Evidence    string
	Reason      string
}

type htmlPage struct {
	Title          string
	Target         string
	Score          int
	Level          string
	LevelLabel     string
	OpenFindings   int
	AcceptedRisks  int
	ConfigPath     string
	GeneratedAt    string
	Summary        string
	NextActions    []string
	Sections       []htmlSection
	AcceptedItems  []htmlFinding
	HasFindings    bool
	HasAccepted    bool
	HasNextActions bool
}

const htmlReportTemplate = `<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<title>{{.Title}}</title>
<style>
:root { color-scheme: light dark; }
body { font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, sans-serif; max-width: 880px; margin: 2rem auto; padding: 0 1.5rem; line-height: 1.5; }
h1 { margin-bottom: 0.25rem; }
h2 { margin-top: 2rem; border-bottom: 1px solid rgba(127,127,127,0.25); padding-bottom: 0.25rem; }
.meta { color: #666; font-size: 0.95rem; margin-bottom: 1.5rem; }
.meta span { margin-right: 1rem; }
.score { font-weight: 600; }
.level { padding: 0.1rem 0.5rem; border-radius: 0.25rem; background: rgba(127,127,127,0.15); }
.summary { background: rgba(127,127,127,0.08); border-left: 3px solid #4a8; padding: 0.75rem 1rem; border-radius: 0.25rem; }
.next-actions { padding-left: 1.25rem; }
.findings { list-style: none; padding-left: 0; }
.finding { border: 1px solid rgba(127,127,127,0.25); border-radius: 0.5rem; padding: 0.75rem 1rem; margin-bottom: 0.75rem; }
.finding code { background: rgba(127,127,127,0.12); padding: 0.05rem 0.35rem; border-radius: 0.25rem; font-size: 0.85em; }
.finding .label { font-size: 0.75rem; text-transform: uppercase; letter-spacing: 0.05em; color: #888; }
.finding .fix { margin-top: 0.4rem; }
.finding .evidence { margin-top: 0.4rem; color: #666; font-size: 0.9em; }
.severity-critical h2 { color: #c33; }
.severity-high h2 { color: #d80; }
.severity-medium h2 { color: #b83; }
.accepted .finding { border-style: dashed; }
footer { margin-top: 3rem; color: #888; font-size: 0.85rem; }
</style>
</head>
<body>
<h1>{{.Title}}</h1>
<p class="meta">
  <span>Target: <code>{{.Target}}</code></span>
  <span class="score">Score: {{.Score}}/100</span>
  <span class="level">{{.LevelLabel}}</span>
  <span>Open: {{.OpenFindings}}</span>
  <span>Accepted: {{.AcceptedRisks}}</span>
  {{if .ConfigPath}}<span>Config: <code>{{.ConfigPath}}</code></span>{{end}}
  <span>Generated: {{.GeneratedAt}}</span>
</p>

<h2>Executive Summary</h2>
<p class="summary">{{.Summary}}</p>

{{if .HasNextActions}}
<h2>Next Actions</h2>
<ol class="next-actions">
{{range .NextActions}}<li>{{.}}</li>{{end}}
</ol>
{{end}}

{{range .Sections}}
<section class="severity-{{.Severity}}">
<h2>{{.Title}}</h2>
<ul class="findings">
{{range .Items}}
<li class="finding">
  <div><strong>{{.Title}}</strong> <code>{{.ID}}</code></div>
  <div>{{.Summary}}</div>
  {{if .Remediation}}<div class="fix"><span class="label">Fix</span> {{.Remediation}}</div>{{end}}
  {{if .Evidence}}<div class="evidence"><span class="label">Evidence</span> {{.Evidence}}</div>{{end}}
</li>
{{end}}
</ul>
</section>
{{end}}

{{if .HasAccepted}}
<section class="accepted">
<h2>Accepted Risks</h2>
<ul class="findings">
{{range .AcceptedItems}}
<li class="finding">
  <div><strong>{{.Title}}</strong> <code>{{.ID}}</code></div>
  {{if .Reason}}<div>{{.Reason}}</div>{{end}}
  {{if .Evidence}}<div class="evidence"><span class="label">Evidence</span> {{.Evidence}}</div>{{end}}
</li>
{{end}}
</ul>
</section>
{{end}}

<footer>Generated by DeployShuttle.</footer>
</body>
</html>
`

func htmlReport(report readiness.Report) (string, error) {
	failed := openFindings(report.Checks)
	ignored := ignoredChecks(report.Checks)
	sections := []htmlSection{}
	for _, severity := range []readiness.Severity{readiness.Critical, readiness.High, readiness.Medium, readiness.Low, readiness.Info} {
		checks := filterChecks(report.Checks, severity, false)
		if len(checks) == 0 {
			continue
		}
		items := make([]htmlFinding, 0, len(checks))
		for _, check := range checks {
			items = append(items, htmlFinding{
				Title:       check.Title,
				ID:          check.ID,
				Summary:     check.Summary,
				Remediation: check.Remediation,
				Evidence:    evidenceSummary(check),
			})
		}
		sections = append(sections, htmlSection{
			Severity: strings.ToLower(string(severity)),
			Title:    strings.Title(string(severity)),
			Items:    items,
		})
	}
	accepted := make([]htmlFinding, 0, len(ignored))
	for _, check := range ignored {
		accepted = append(accepted, htmlFinding{
			Title:    check.Title,
			ID:       check.ID,
			Reason:   check.IgnoreReason,
			Evidence: evidenceSummary(check),
		})
	}
	page := htmlPage{
		Title:          "DeployShuttle Production Readiness Report",
		Target:         report.Target,
		Score:          report.Score,
		Level:          string(report.Level),
		LevelLabel:     readiness.LevelLabel(report.Level),
		OpenFindings:   len(failed),
		AcceptedRisks:  len(ignored),
		ConfigPath:     report.ConfigPath,
		GeneratedAt:    report.GeneratedAt,
		Summary:        executiveSummary(report),
		NextActions:    nextActions(failed),
		Sections:       sections,
		AcceptedItems:  accepted,
		HasFindings:    len(sections) > 0,
		HasAccepted:    len(accepted) > 0,
		HasNextActions: len(nextActions(failed)) > 0,
	}
	tpl, err := template.New("report").Parse(htmlReportTemplate)
	if err != nil {
		return "", fmt.Errorf("parse html template: %w", err)
	}
	var buf bytes.Buffer
	if err := tpl.Execute(&buf, page); err != nil {
		return "", fmt.Errorf("render html template: %w", err)
	}
	return buf.String(), nil
}
