package templates

import (
	"fmt"
	"strings"

	"github.com/MakFly/deploy-shuttle/go-cli/internal/config"
)

// ReadinessPresets enumerates the supported `init --preset` values.
var ReadinessPresets = []string{"nextjs", "laravel", "node-api", "docker-swarm"}

// IsReadinessPreset reports whether name is a supported preset.
func IsReadinessPreset(name string) bool {
	for _, p := range ReadinessPresets {
		if p == name {
			return true
		}
	}
	return false
}

// DeployShuttleYML returns an opinionated `.shuttle.yml` for the given
// preset. domain may be empty; it is rendered as a placeholder users can edit.
func DeployShuttleYML(preset string, domain string) string {
	if domain == "" {
		domain = "app.example.com"
	}
	switch preset {
	case "nextjs":
		return fmt.Sprintf(`version: 1

# Generated by 'shuttle init --preset nextjs'.
# Adjust app.domain and ignore lists as the project evolves.

app:
  domain: %s
  healthcheckPath: /api/health

checks:
  profile: [docker, caddy]
  ignore:
    # Adminer is rare in a Next.js stack; remove this line if you ship one.
    - adminer.ip_restriction_missing

docker:
  # No long-running queue workers in a typical Next.js setup.
  workerServices: []
`, domain)

	case "laravel":
		return fmt.Sprintf(`version: 1

# Generated by 'shuttle init --preset laravel'.
# Tune the queue / horizon / scheduler patterns to your container naming.

app:
  domain: %s
  healthcheckPath: /up

checks:
  profile: [docker, caddy]

docker:
  # Laravel queue workers, Horizon supervisors, and schedulers do not expose
  # an HTTP healthcheck; treat them as workers so doctor stops flagging them.
  workerServices:
    - "*-queue"
    - "*-horizon"
    - "*-scheduler"
    - "*-worker"
  # Octane / RoadRunner images sometimes require root; allow-list as needed.
  allowRoot: []
  # Dozzle / log shippers that legitimately mount the Docker socket.
  allowDockerSocket:
    - dozzle*
`, domain)

	case "node-api":
		return fmt.Sprintf(`version: 1

# Generated by 'shuttle init --preset node-api'.

app:
  domain: %s
  healthcheckPath: /health

checks:
  profile: [docker, caddy]
  ignore:
    - adminer.ip_restriction_missing

docker:
  workerServices: []
`, domain)

	case "docker-swarm":
		return fmt.Sprintf(`version: 1

# Generated by 'shuttle init --preset docker-swarm'.
# Worker patterns assume the common '<stack>_<role>' Swarm naming.

app:
  domain: %s
  healthcheckPath: /health

checks:
  profile: [docker, caddy]

docker:
  workerServices:
    - "*_worker"
    - "*_consumer"
    - "*_scheduler"
    - "*_cron"
  allowDockerSocket:
    - dozzle*
    - portainer_agent*
`, domain)
	}
	return ""
}

func ShuttleYML(app string, domain string, host string, user string, port int) string {
	if port == 0 {
		port = 22
	}
	return fmt.Sprintf(`app: %s
domain: %s
server:
  host: %s
  user: %s
  port: %d

deploy:
  strategy: compose

services:
  web:
    port: 3000
`, app, domain, host, user, port)
}

func Caddyfile(cfg *config.Config, upstream string) string {
	domains := Domains(cfg)
	var b strings.Builder
	for _, domain := range domains {
		fmt.Fprintf(&b, "%s {\n", domain)
		if len(cfg.Proxy.Headers) > 0 {
			b.WriteString("  header {\n")
			for key, value := range cfg.Proxy.Headers {
				fmt.Fprintf(&b, "    %s %s\n", key, value)
			}
			b.WriteString("  }\n")
		}
		fmt.Fprintf(&b, "  reverse_proxy %s\n", upstream)
		b.WriteString("}\n\n")
	}
	return b.String()
}

func ComposeDev(cfg *config.Config) string {
	var b strings.Builder
	b.WriteString("services:\n")
	for name, service := range cfg.Services {
		fmt.Fprintf(&b, "  %s:\n", name)
		b.WriteString("    build: .\n")
		if service.Command != "" {
			fmt.Fprintf(&b, "    command: %q\n", service.Command)
		}
		if service.Port != 0 {
			fmt.Fprintf(&b, "    ports:\n      - %q\n", fmt.Sprintf("%d:%d", service.Port, service.Port))
		}
	}
	return b.String()
}

func Domains(cfg *config.Config) []string {
	switch v := cfg.Domain.(type) {
	case string:
		return []string{v}
	case []any:
		out := []string{}
		for _, item := range v {
			if s, ok := item.(string); ok {
				out = append(out, s)
			}
		}
		return out
	case []string:
		return v
	default:
		return []string{}
	}
}
