package license

import (
	"encoding/base64"
	"errors"
	"testing"
	"time"
)

// Test vector: token + matching public key generated by the Bun-based license
// server's signToken() in license-server/src/lib/jwt.ts. Locks down the
// byte-level wire contract so any divergence in JSON encoding, base64url
// alphabet, or signing payload shape will fail this test.
func TestCrossCompatVerifyBunSignedToken(t *testing.T) {
	const pubB64 = "qXKxrQF5c535be5zol/2S/k85lchloV1htONr3Z9Yqo="
	const token = "eyJhbGciOiJFZERTQSIsInR5cCI6IkpXVCJ9.eyJrZXkiOiJEUy1BQUFBQUEtQkJCQkJCLUNDQ0NDQyIsInRpZXIiOiJwcm8iLCJmcCI6ImZwLWRlYWRiZWVmIiwiaWF0IjoxNzMwMDAwMDAwLCJleHAiOjE3MzEyMDk2MDB9.2SKiSro13XR9047s-mTAGLSeDZqs09Sgqa0tn_AFsdHFQmdIhoWc7xql9maef1uKJ-VQ-_1Q2qy-ippp4KcGBA"

	rawPub, err := base64.StdEncoding.DecodeString(pubB64)
	if err != nil {
		t.Fatalf("decode pub: %v", err)
	}

	now := time.Unix(1_730_500_000, 0).UTC() // between iat and exp
	out, err := VerifyToken(token, rawPub, now, "fp-deadbeef")
	if err != nil {
		t.Fatalf("verify: %v", err)
	}
	if out.Key != "DS-AAAAAA-BBBBBB-CCCCCC" || out.Tier != "pro" || out.FP != "fp-deadbeef" {
		t.Fatalf("unexpected claims: %+v", out)
	}
	if out.IAT != 1_730_000_000 || out.EXP != 1_731_209_600 {
		t.Fatalf("unexpected iat/exp: %+v", out)
	}
}

// Sanity: same token with wrong fingerprint must fail.
func TestCrossCompatRejectsForeignFingerprint(t *testing.T) {
	const pubB64 = "qXKxrQF5c535be5zol/2S/k85lchloV1htONr3Z9Yqo="
	const token = "eyJhbGciOiJFZERTQSIsInR5cCI6IkpXVCJ9.eyJrZXkiOiJEUy1BQUFBQUEtQkJCQkJCLUNDQ0NDQyIsInRpZXIiOiJwcm8iLCJmcCI6ImZwLWRlYWRiZWVmIiwiaWF0IjoxNzMwMDAwMDAwLCJleHAiOjE3MzEyMDk2MDB9.2SKiSro13XR9047s-mTAGLSeDZqs09Sgqa0tn_AFsdHFQmdIhoWc7xql9maef1uKJ-VQ-_1Q2qy-ippp4KcGBA"

	rawPub, _ := base64.StdEncoding.DecodeString(pubB64)
	now := time.Unix(1_730_500_000, 0).UTC()
	_, err := VerifyToken(token, rawPub, now, "wrong-fp")
	if !errors.Is(err, ErrFingerprintMismatch) {
		t.Fatalf("expected ErrFingerprintMismatch, got %v", err)
	}
}
